setup.dashboards.enabled: false
setup.template.enabled: false

setup.template.settings:
  index.number_of_shards: 1

filebeat.modules:
  - module: system
    syslog:
      enabled: true
      #var.paths: ["/var/log/syslog"]
    auth:
      enabled: true
      #var.paths: ["/var/log/authlog"]

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: elasticsearch
          config:
            - module: elasticsearch
        - condition:
            contains:
              docker.container.image: kibana
          config:
            - module: kibana
        - condition:
            contains:
              docker.container.image: redis
          config:
            - module: redis
              log:
                input:
                  type: docker
                  containers.ids:
                    - "${data.docker.container.id}"
              slowlog:
                enabled: true
                var.hosts: ["${data.host}:${data.port}"]

processors:
  - add_cloud_metadata:
  - add_docker_metadata:


output.elasticsearch:
  hosts: ["elasticsearch:9200"]
      
setup.kibana:
  host: "kibana:5601"
